# Generated by Django 3.1.1 on 2020-09-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=200)),
                ('exercise_added', models.DateTimeField(verbose_name='Date exercise added')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_list_name', models.CharField(max_length=200)),
                ('practice_list_created', models.DateTimeField(verbose_name='Date the list has been created.')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=200)),
                ('reference_ISBN', models.CharField(blank=True, max_length=500, null=True)),
                ('reference_author', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExercisePracticeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progressTracker.exercise')),
                ('practice_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progressTracker.practicelist')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progressTracker.reference'),
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_start', models.DateTimeField(verbose_name='DateTime practice started')),
                ('execution_end', models.DateTimeField(verbose_name='DateTime practice ended')),
                ('execution_rating', models.IntegerField(default=5)),
                ('execution_tempo', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progressTracker.exercise')),
            ],
        ),
    ]
