# Generated by Django 3.1.1 on 2020-09-19 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=200)),
                ('exercise_add_date', models.DateField(verbose_name='Date exercise added')),
                ('exercise_executed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_session_start', models.DateTimeField(verbose_name='DateTime practice started')),
                ('practice_session_end', models.DateTimeField(verbose_name='DateTime practice ended')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progressTracker.exercise')),
            ],
        ),
    ]
