# Generated by Django 3.1.1 on 2020-09-26 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='execution_rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='execution',
            name='execution_tempo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
