# Generated by Django 3.1.1 on 2020-09-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_times_executed',
        ),
        migrations.AlterField(
            model_name='exercisereference',
            name='exercise_reference_ISBN',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exercisereference',
            name='exercise_reference_author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
