# Generated by Django 3.1.1 on 2020-09-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_add_date',
            field=models.DateTimeField(verbose_name='Date exercise added'),
        ),
    ]
