# Generated by Django 3.1.1 on 2020-09-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressTracker', '0002_auto_20200920_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='execution_tempo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
