# Generated by Django 3.1.1 on 2020-09-26 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progressTracker', '0002_auto_20200926_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_type', models.CharField(max_length=200)),
                ('instrument_brand', models.CharField(max_length=200)),
                ('instrument_description', models.CharField(max_length=200)),
                ('instrument_date_bought', models.DateTimeField()),
                ('instrument_price', models.FloatField(default=0)),
                ('instrument_store', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='execution',
            name='instrument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='progressTracker.instrument'),
            preserve_default=False,
        ),
    ]
