# Generated by Django 3.1.1 on 2020-09-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progressTracker', '0003_auto_20200926_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_brand',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_date_bought',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_store',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progressTracker.exercise')),
            ],
        ),
    ]
