# Generated by Django 3.1.1 on 2020-09-20 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progressTracker', '0003_auto_20200919_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=200)),
                ('reference_ISBN', models.CharField(max_length=500, null=True)),
                ('reference_author', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='practice_reference',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='progressTracker.practicereference'),
            preserve_default=False,
        ),
    ]
