# Generated by Django 3.1.1 on 2020-09-27 07:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progressTracker', '0004_auto_20200927_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercisecategory',
            name='category_name',
        ),
        migrations.AddField(
            model_name='exercisecategory',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='progressTracker.category'),
            preserve_default=False,
        ),
    ]
