# Generated by Django 3.1.1 on 2020-09-27 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progressTracker', '0005_auto_20200927_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progressTracker.category'),
        ),
    ]
