# Generated by Django 3.1.1 on 2020-09-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressTracker', '0006_auto_20200927_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='execution_tempo',
            field=models.PositiveIntegerField(),
        ),
    ]
